CREATE TABLE flights (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    departure_airport TEXT,
    arrival_airport TEXT,
    company TEXT,
    arrival_time TIME,
    departure_time TIME,
    user_id INTEGER REFERENCES flight_users(id)
    ON DELETE SET NULL
);